Added availability set for workers and security group to allow ingress access
kubermatic/kubeone pull request #1556
Opened 2021-10-01 05:10 UTC by dharapvj

**What this PR does / why we need it**:
Currently, Azure terraform example has two issues:
1. If we install any service of type LoadBalancer, it does not provide LoadBalancer. this is because of Azure having some restriction on number of LoadBalancers in a given availability set. We are having a single AV set in the code for masters as well as workers and we already provision one load balancer for api-server. So we cannot provision any service of type LoadBalancer (e.g. nginx ingress)
2. If we get 2nd AVset for above issue and then install nginx-ingress, we cannot reach the ingress endpoints due to security group restrictions.

This PR solves both above issues by adding an additional avset for worker machines and also relaxing security group to reach on port 80 and 443 from LB.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:
Partially related #1307 . Need documentation fix though.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2021-10-01 10:36 UTC, xmudrii requested changes
Can you please edit the PR description to replace `Fixes #...` with `xref #...`? I don't want to close the issue yet because I think this should also be documented. I'll take care of the docs later.

2021-10-05 09:20 UTC, dharapvj commented on examples/terraform/azure/output.tf
> +          availabilitySet   = azurerm_availability_set.avset_worker.name
Done.

2021-10-05 09:20 UTC, dharapvj commented on examples/terraform/azure/main.tf
> +  }
Done. Removed.

2021-10-05 09:21 UTC, dharapvj commented on examples/terraform/azure/main.tf
> +  name                         = "${var.cluster_name}-avset-worker"
Done.

2021-10-05 09:21 UTC, xmudrii commented on examples/terraform/azure/main.tf
> +
Tiny nit: can you remove this space?

2021-10-05 09:24 UTC, dharapvj commented on examples/terraform/azure/main.tf
> +
Done.

2021-10-05 09:24 UTC, xmudrii approved these changes
Thanks, @dharapvj!

2021-10-05 09:38 UTC, xmudrii commented
/approve

2021-10-05 09:39 UTC, merged

2021-10-05 12:39 UTC, xmudrii commented
/cherrypick release/v1.3