Domain is not required when using application credentials
kubermatic/kubeone pull request #1896
Opened 2022-03-17 16:07 UTC by ahmedwaleedmalik

**What does this PR do / Why do we need it**:
Domain is not required when using application credentials.

**Does this PR close any issues?**:
Fixes #1872

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
* Domain is not required when using application credentials
```

2022-03-17 16:07 UTC, ahmedwaleedmalik commented
/hold

Requires version bump for machine-controller

2022-03-18 09:22 UTC, kron4eg approved these changes

2022-03-18 09:23 UTC, kron4eg commented
/kind feature

2022-03-18 10:25 UTC, xmudrii approved these changes

2022-04-01 09:36 UTC, ahmedwaleedmalik commented
/unhold

2022-04-01 09:37 UTC, xmudrii approved these changes

2022-04-01 09:38 UTC, ahmedwaleedmalik commented
/cherrypick release/v1.4

2022-04-01 12:36 UTC, xmudrii commented
/retest

2022-04-04 12:28 UTC, kron4eg requested changes
please move spotInstance bits into dedicated PR.

2022-04-04 12:42 UTC, ahmedwaleedmalik commented
MC and spot instance relevant changes moved to https://github.com/kubermatic/kubeone/pull/1924

2022-04-04 12:42 UTC, ahmedwaleedmalik commented
/hold depends on https://github.com/kubermatic/kubeone/pull/1924

2022-04-05 08:39 UTC, kron4eg commented
/lgtm
/approve
/retest

2022-04-05 08:41 UTC, kron4eg approved these changes

2022-04-07 11:02 UTC, ahmedwaleedmalik commented
/unhold

2022-04-07 11:56 UTC, merged