Add vsphere anit-affinity rule to terraform example
kubermatic/kubeone pull request #2124
Opened 2022-06-28 12:28 UTC by mihiragrawal

**What type of PR is this?**

kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** :

This PR adds the vsphere anti-affinity rule to terraform example so control planes can spread across the hosts. 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2022-06-29 09:43 UTC, kron4eg requested changes
Please add:
* proper kind (with slash)
* proper release-note (how is this a kind feature but how no release-note?)
* sync this change to vsphere-flatcar configuration too

2022-06-30 07:16 UTC, mihiragrawal commented on examples/terraform/vsphere/main.tf
> +  virtual_machine_ids = [for k, v in vsphere_virtual_machine.control_plane : v.id]
Fixed. Thanks for the suggestions.

2022-06-30 07:48 UTC, kron4eg commented
/kind feature

2022-06-30 07:48 UTC, kron4eg commented
/approve
/lgtm

2022-06-30 07:49 UTC, merged