Uninstall helm release that was installed by kubeone but is not listed anymore in the Manifest
kubermatic/kubeone pull request #2522
Opened 2022-12-02 13:03 UTC by kron4eg

**Which issue(s) this PR fixes**:
Fixes #2516 

**What type of PR is this?**
/kind feature

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Uninstall helm release that was installed by kubeone but is not listed anymore in the Manifest
```

**Documentation**:

```documentation
TBD
```

2022-12-06 18:38 UTC, xmudrii requested changes
Some nits, but other than that, looks good to me.

2022-12-06 22:23 UTC, kron4eg commented on pkg/localhelm/helm3.go
> +		st.Logger.Debugf("uninstalling helm release %s/%s: %s", rel.Namespace, rel.Name, resp.Info)
✓

2022-12-06 22:23 UTC, kron4eg commented on pkg/localhelm/helm3.go
> +	releaseSecret.Labels[releasedByKubeone] = "yes"
The value here is not important absolutely, so I've replaced it with empty value.

2022-12-07 08:49 UTC, xmudrii approved these changes
/lgtm
/approve

2022-12-07 08:49 UTC, merged