Update hetzner CCM v1.15.0
kubermatic/kubeone pull request #2774
Opened 2023-04-21 10:04 UTC by kron4eg

**What this PR does / why we need it**:
Update hetzner CCM to 1.15.0 to gain access to ARM instances

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubermatic/kubeone/discussions/2773

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
New Hetzner ARM instances
```

**Documentation**:
```documentation
NONE
```

2023-04-21 10:06 UTC, xrstf commented
/test

2023-04-21 10:06 UTC, xrstf commented
/test pull-kubeone-e2e-hetzner-default-install-containerd-external-v1.24.10
/test pull-kubeone-e2e-hetzner-default-install-containerd-external-v1.25.6
/test pull-kubeone-e2e-hetzner-default-install-containerd-external-v1.26.1

2023-04-24 20:25 UTC, xrstf commented
/test pull-kubeone-e2e-hetzner-default-install-containerd-external-v1.25.6

2023-04-24 20:53 UTC, xrstf commented
All CSI related components just log

```
W0424 20:34:10.021292       1 connection.go:173] Still connecting to unix:///run/csi/socket
W0424 20:34:20.022229       1 connection.go:173] Still connecting to unix:///run/csi/socket
W0424 20:34:30.021478       1 connection.go:173] Still connecting to unix:///run/csi/socket
W0424 20:34:40.021888       1 connection.go:173] Still connecting to unix:///run/csi/socket
W0424 20:34:50.022287       1 connection.go:173] Still connecting to unix:///run/csi/socket
```

ad infinitum

2023-04-24 21:01 UTC, xmudrii commented
/test pull-kubeone-e2e-hetzner-default-install-containerd-external-v1.25.6

2023-04-24 21:04 UTC, xmudrii commented
/test pull-kubeone-e2e-hetzner-default-install-containerd-external-v1.25.6

2023-04-24 21:24 UTC, xmudrii requested changes

2023-04-24 21:24 UTC, xmudrii commented on pkg/templates/images/images.go
> +		HetznerCSI:                   {"*": "docker.io/hetznercloud/hcloud-csi-driver:2.3.2"},
This should be prefixed with `v`, see https://hub.docker.com/layers/hetznercloud/hcloud-csi-driver/v2.3.2/images/sha256-0ed4f2f51459466f994c2ce6a566819e61c6dda26c1312d4e36172b74ea97d9d?context=explore

```suggestion
		HetznerCSI:                   {"*": "docker.io/hetznercloud/hcloud-csi-driver:v2.3.2"},
```

2023-04-24 21:26 UTC, xmudrii commented on pkg/templates/images/images.go
> +		HetznerCSI:                   {"*": "docker.io/hetznercloud/hcloud-csi-driver:2.3.2"},
Additional reference (thanks @xrstf): https://github.com/hetznercloud/csi-driver/pull/407/files

2023-04-25 06:38 UTC, kron4eg commented
/test pull-kubeone-e2e-hetzner-default-install-containerd-external-v1.25.6

2023-04-25 08:15 UTC, kron4eg commented
@xmudrii @xrstf now it's passing!

2023-04-25 08:17 UTC, xmudrii approved these changes
/approve

2023-04-25 08:56 UTC, merged