Upgrade to latest MC image
kubermatic/kubeone pull request #3213
Opened 2024-06-06 10:29 UTC by ahmedwaleedmalik

**What this PR does / why we need it**:
Upgrading MC to https://github.com/kubermatic/machine-controller/commit/d62ab03c71afd83c2d13549b06f85bd4621ef186 and removing all the deprecated flags for MC deployment.

I'm intentionally not updating the go dependency since that'd require k8s API etc to be bumped as well. 

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```
/assign
/cc @kron4eg

2024-06-06 11:37 UTC, xmudrii requested changes
Can you also please remove legacy MC tests from `tests.yml` (including relevant scenario and infrastructure)?

2024-06-06 11:37 UTC, xmudrii commented on addons/machinecontroller/deployment-controller.yaml
> -            - -cluster-dns={{ .Resources.NodeLocalDNSVirtualIP }}
FYI: This flag is not marked as deprecated in MC but seems to be no-op.

2024-06-06 13:16 UTC, xmudrii commented
@ahmedwaleedmalik Can you also remove:
- https://github.com/kubermatic/kubeone/blob/b9768c8495faab44e8441df72ee625233a5ad968/test/e2e/tests_definitions.go#L1413-L1420
- https://github.com/kubermatic/kubeone/blob/main/test/e2e/testdata/legacy_machine_controller_containerd_external.yaml

2024-06-06 13:22 UTC, ahmedwaleedmalik commented
> * legacy_machine_controller_containerd_external

Marko, I will, but please keep in mind that this PR was only to ensure that the flags were correct.

2024-06-06 13:43 UTC, ahmedwaleedmalik commented
/hold
Some indentation issue in the webhook.yaml, will check back later.

2024-06-06 18:11 UTC, ahmedwaleedmalik commented
/unhold

2024-06-11 10:24 UTC, xmudrii approved these changes
/lgtm
/approve

2024-06-11 10:24 UTC, merged