Validate MachineController/OperatingSystemManager and cloudProvider None are mutually exclusive
kubermatic/kubeone pull request #3369
Opened 2024-09-13 10:05 UTC by kron4eg

**Which issue(s) this PR fixes**:

Fixes #3366

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Validate MachineController/OperatingSystemManager and cloudProvider None are mutually exclusive
```

**Documentation**:

```documentation
NONE
```

2024-09-17 09:38 UTC, xmudrii requested changes
As stated in https://github.com/kubermatic/kubeone/issues/3366#issuecomment-2355058729, we shouldn't forbid this, but properly handle it

2025-01-13 01:17 UTC, kron4eg commented
Since we got #3416, this PR can be merge too.

2025-01-13 09:29 UTC, xmudrii commented
@kron4eg Yes, we can proceed if you want.

2025-01-13 09:49 UTC, xmudrii approved these changes
/lgtm
/approve

2025-01-13 09:51 UTC, xmudrii commented
/remove-kind bug
/kind api-change
/release-note-edit
```release-note
[ACTION REQUIRED] Disallow using machine-controller and operating-system-manager with the cloud provider `none` (`.cloudProvider.none`). If you're affected by this change, you have to either disable machine-controller and/or operating-system-manager, or switch from cloud provider none to a supported cloud provider. This affects both KubeOneCluster v1beta2 and v1beta3 APIs.
```

2025-01-13 10:17 UTC, merged